################################# Default configuration ###################
baseURL = "https://dcc-iaps.github.io/dcc-iaps/"
title = "DCC | Decoders of the Cosmic Code"
theme = "meghna-hugo"
publishDir = "docs"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

############################# Navigation ##################################
[[menu.main]]
name = "About Us"
URL = "about"
weight = 1

[[menu.main]]
name = "Goals"
URL = "services"
weight = 2

[[menu.main]]
name = "Activities"
URL = "portfolio"
weight = 3

[[menu.main]]
name = "Members"
URL = "team"
weight = 4

[[menu.main]]
name = "Founders"
URL = "pricing"
weight = 5

[[menu.main]]
name = "Blog"
URL = "blog"
weight = 6

[[menu.main]]
name = "Contact"
URL = "contact"
weight = 7

#### external / static link ####
[[menu.static]]
name = "Themefisher"
URL = "https://themefisher.com/"
weight = 8

############################# Default Parameters ##########################
[params]
logo = "images/dcc_light.png"
# Meta data
description = "Responsive Multipurpose Parallax HTML5 Template"
author = "Themefisher"
# Google Analitycs
google_analitycs_id = "" # Your ID
# post share
post_share = true

# preloader
[params.preloader]
enable = true
preloader = "images/custom_preloader.gif"

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyAX5IaeXXbjgbU_KfAdvoAonOvZQUvkekc"
map_latitude = "28.618873"
map_longitude = "77.200519"
map_marker = "images/marker1.png"

############################# social icons ##########################
[[params.social]]
icon = "ti-facebook" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-twitter-alt" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-youtube" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-linkedin" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-dribbble" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-pinterest" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-instagram" # themify icon pack : https://themify.me/themify-icons
link = "#"

[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
link = "#"


################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
copyright = "copyright &copy; 2020 [DCC | LC-New Delhi](https://gethugothemes.com) all right reserved"

################################ France Language ########################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
home = "Accueil"
copyright = "copyright et copie; 2020 [DCC | LC-New Delhi] (https://gethugothemes.com) tous droits réservés"